export enum ErrorCode {
  // Generic (derived from the HTTP status)
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Database-level
  UNIQUE_VIOLATION = 'UNIQUE_VIOLATION',
  REFERENCED_RECORD = 'REFERENCED_RECORD',
  CHECK_VIOLATION = 'CHECK_VIOLATION',
  NOT_NULL_VIOLATION = 'NOT_NULL_VIOLATION',
  VALUE_TOO_LONG = 'VALUE_TOO_LONG',
  INVALID_IDENTIFIER = 'INVALID_IDENTIFIER',

  // Auth
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  INVALID_OTP = 'INVALID_OTP',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  CURRENT_PASSWORD_INCORRECT = 'CURRENT_PASSWORD_INCORRECT',
  PASSWORD_UNCHANGED = 'PASSWORD_UNCHANGED',
  NO_PASSWORD_SET = 'NO_PASSWORD_SET',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',

  // Users
  CANNOT_DEACTIVATE_SELF = 'CANNOT_DEACTIVATE_SELF',
  CANNOT_CHANGE_OWN_ROLE = 'CANNOT_CHANGE_OWN_ROLE',
  NO_AVATAR = 'NO_AVATAR',

  // Properties & units
  OWNER_REQUIRED = 'OWNER_REQUIRED',
  OWNER_INVALID = 'OWNER_INVALID',
  PROPERTY_HAS_RENTED_UNITS = 'PROPERTY_HAS_RENTED_UNITS',
  PROPERTY_ACCESS_DENIED = 'PROPERTY_ACCESS_DENIED',
  PROPERTY_NOT_FOUND = 'PROPERTY_NOT_FOUND',
  UNIT_NUMBER_TAKEN = 'UNIT_NUMBER_TAKEN',
  UNIT_RENTED = 'UNIT_RENTED',
  UNIT_STATUS_TRANSITION_INVALID = 'UNIT_STATUS_TRANSITION_INVALID',
  UNIT_HAS_LEASES = 'UNIT_HAS_LEASES',
  UNIT_HAS_RENTAL_REQUESTS = 'UNIT_HAS_RENTAL_REQUESTS',
  UNIT_HAS_MAINTENANCE_REQUESTS = 'UNIT_HAS_MAINTENANCE_REQUESTS',
  UNIT_NOT_AVAILABLE = 'UNIT_NOT_AVAILABLE',
  UNIT_NOT_FOUND = 'UNIT_NOT_FOUND',
  UNIT_ACCESS_DENIED = 'UNIT_ACCESS_DENIED',

  // Dates
  INVALID_DATE = 'INVALID_DATE',
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
  END_DATE_IN_PAST = 'END_DATE_IN_PAST',

  // Rental requests
  RENTAL_REQUEST_DUPLICATE_PENDING = 'RENTAL_REQUEST_DUPLICATE_PENDING',
  RENTAL_REQUEST_NOT_PENDING = 'RENTAL_REQUEST_NOT_PENDING',
  RENTAL_REQUEST_PERIOD_ENDED = 'RENTAL_REQUEST_PERIOD_ENDED',
  TENANT_NOT_ACTIVE = 'TENANT_NOT_ACTIVE',
  RENTAL_REQUEST_NOT_FOUND = 'RENTAL_REQUEST_NOT_FOUND',
  RENTAL_REQUEST_ACCESS_DENIED = 'RENTAL_REQUEST_ACCESS_DENIED',

  // Leases
  LEASE_NOT_FOUND = 'LEASE_NOT_FOUND',
  LEASE_DATES_OVERLAP = 'LEASE_DATES_OVERLAP',
  LEASE_NOT_PENDING = 'LEASE_NOT_PENDING',
  LEASE_NOT_ACTIVE = 'LEASE_NOT_ACTIVE',
  LEASE_NOT_TERMINABLE = 'LEASE_NOT_TERMINABLE',
  RENEWAL_END_NOT_AFTER_CURRENT = 'RENEWAL_END_NOT_AFTER_CURRENT',
  RENEWAL_REQUEST_DUPLICATE_PENDING = 'RENEWAL_REQUEST_DUPLICATE_PENDING',
  RENEWAL_REQUEST_NOT_PENDING = 'RENEWAL_REQUEST_NOT_PENDING',
  LEASE_ACCESS_DENIED = 'LEASE_ACCESS_DENIED',

  // Maintenance
  NO_ACTIVE_LEASE = 'NO_ACTIVE_LEASE',
  STAFF_INVALID = 'STAFF_INVALID',
  NOT_ASSIGNED_STAFF = 'NOT_ASSIGNED_STAFF',
  MAINTENANCE_INVALID_STATE = 'MAINTENANCE_INVALID_STATE',

  // Images / pagination
  IMAGE_REQUIRED = 'IMAGE_REQUIRED',
  IMAGE_LIMIT_EXCEEDED = 'IMAGE_LIMIT_EXCEEDED',
  IMAGE_TOO_LARGE = 'IMAGE_TOO_LARGE',
  IMAGE_INVALID = 'IMAGE_INVALID',
  IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
  INVALID_SORT_FIELD = 'INVALID_SORT_FIELD',
}
