export enum AuditAction {
  PROPERTY_CREATED = 'PROPERTY_CREATED',
  PROPERTY_DELETED = 'PROPERTY_DELETED',
  LEASE_CREATED = 'LEASE_CREATED',
  LEASE_ACTIVATED = 'LEASE_ACTIVATED',
  LEASE_TERMINATED = 'LEASE_TERMINATED',
  USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',
  UNIT_STATUS_CHANGED = 'UNIT_STATUS_CHANGED',
  MAINTENANCE_ASSIGNED = 'MAINTENANCE_ASSIGNED',
  MAINTENANCE_COMPLETED = 'MAINTENANCE_COMPLETED',
  ROLE_CHANGED = 'ROLE_CHANGED',
}
