export enum NotificationType {
  LEASE_CREATED = 'LEASE_CREATED',
  LEASE_ACTIVATED = 'LEASE_ACTIVATED',
  LEASE_TERMINATED = 'LEASE_TERMINATED',
  MAINTENANCE_CREATED = 'MAINTENANCE_CREATED',
  MAINTENANCE_ASSIGNED = 'MAINTENANCE_ASSIGNED',
  MAINTENANCE_RESOLVED = 'MAINTENANCE_RESOLVED',
}
